excludes = [".git/*", "result", "*.lock", "*.patch", "lefthook.yml"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
includes = ["*.json", "*.md", "*.yaml", "*.yml"]
excludes = ["r2-explorer/pnpm-lock.yaml"]
options = ["--write"]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh", "*.bash"]
options = ["-w", "-i", "2", "-s"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.actionlint]
command = "actionlint"
includes = [
  ".github/workflows/*.yml",
  ".github/workflows/*.yaml",
  "r2-explorer/.github/workflows/*.yml",
  "r2-explorer/.github/workflows/*.yaml",
]
